import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, Filter, Calendar } from 'lucide-react';
import { Card } from '../components/ui/Card';
import { MOCK_LOANS } from '../constants';
import { Loan } from '../types';

interface ReportsViewProps {
    loans: Loan[];
}

const ReportsView: React.FC<ReportsViewProps> = ({ loans }) => {
  const [generating, setGenerating] = useState<string | null>(null);

  const handleDownload = (reportId: string) => {
    setGenerating(reportId);
    setTimeout(() => {
        setGenerating(null);
        alert("Report downloaded successfully!");
    }, 2000);
  };

  const reports = [
    { id: 'r1', title: 'Portfolio Compliance Summary', type: 'PDF', desc: 'Complete overview of all active loans and covenant statuses.' },
    { id: 'r2', title: 'Risk Assessment Matrix', type: 'CSV', desc: 'Raw data export of risk scores and financial metrics.' },
    { id: 'r3', title: 'Monthly Covenant Digest', type: 'PDF', desc: 'Detailed breakdown of covenants due in the current month.' },
    { id: 'r4', title: 'Audit Trail Log', type: 'CSV', desc: 'History of all changes and compliance checks performed.' },
  ];

  return (
    <div className="p-6 md:p-10 max-w-7xl mx-auto">
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-10">
        <div>
           <h1 className="text-3xl font-bold text-white tracking-tight">Reports Center</h1>
           <p className="text-slate-400 mt-1">Generate and export insights for stakeholders.</p>
        </div>
        <div className="flex gap-3">
             <button className="flex items-center gap-2 px-4 py-2 bg-slate-900 border border-slate-700 rounded-lg text-slate-300 hover:text-white transition-colors">
                <Calendar className="w-4 h-4" /> Last 30 Days
             </button>
             <button className="flex items-center gap-2 px-4 py-2 bg-slate-900 border border-slate-700 rounded-lg text-slate-300 hover:text-white transition-colors">
                <Filter className="w-4 h-4" /> Filter
             </button>
        </div>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reports.map((report) => (
            <Card key={report.id} className="hover:border-emerald-500/30 transition-all">
                <div className="flex items-start justify-between mb-4">
                    <div className="p-3 bg-slate-800 rounded-lg text-emerald-400">
                        <FileText className="w-6 h-6" />
                    </div>
                    <span className="px-2 py-1 text-xs font-medium bg-slate-800 text-slate-400 rounded border border-slate-700">{report.type}</span>
                </div>
                <h3 className="text-lg font-bold text-white mb-2">{report.title}</h3>
                <p className="text-slate-400 text-sm mb-6 h-10">{report.desc}</p>
                
                <button 
                    onClick={() => handleDownload(report.id)}
                    disabled={!!generating}
                    className="w-full flex items-center justify-center gap-2 py-2.5 bg-slate-800 hover:bg-slate-700 text-white rounded-lg border border-slate-700 transition-all disabled:opacity-70"
                >
                    {generating === report.id ? (
                        <>
                             <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                             Generating...
                        </>
                    ) : (
                        <>
                            <Download className="w-4 h-4" /> Download Report
                        </>
                    )}
                </button>
            </Card>
        ))}
      </div>

      <h2 className="text-xl font-bold text-white mt-12 mb-6">Recent Exports</h2>
      <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden">
         <table className="w-full text-left text-sm text-slate-400">
            <thead className="bg-slate-950/50 text-slate-200 font-medium uppercase text-xs">
                <tr>
                    <th className="px-6 py-4">Report Name</th>
                    <th className="px-6 py-4">Date</th>
                    <th className="px-6 py-4">Generated By</th>
                    <th className="px-6 py-4">Status</th>
                </tr>
            </thead>
            <tbody className="divide-y divide-slate-800">
                <tr>
                    <td className="px-6 py-4 text-white">Portfolio Compliance Summary</td>
                    <td className="px-6 py-4">Oct 24, 2024</td>
                    <td className="px-6 py-4">Admin User</td>
                    <td className="px-6 py-4"><span className="text-emerald-400">Completed</span></td>
                </tr>
                <tr>
                    <td className="px-6 py-4 text-white">Risk Assessment Matrix</td>
                    <td className="px-6 py-4">Oct 20, 2024</td>
                    <td className="px-6 py-4">Admin User</td>
                    <td className="px-6 py-4"><span className="text-emerald-400">Completed</span></td>
                </tr>
            </tbody>
         </table>
      </div>
    </div>
  );
};

export default ReportsView;
